package com.my.nullpointerplayer.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.my.nullpointerplayer.db.FindFragmentData;
import com.my.nullpointerplayer.db.RecommendFragmentData;

import com.my.nullpointerplayer.db.FindFragmentDataDao;
import com.my.nullpointerplayer.db.RecommendFragmentDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig findFragmentDataDaoConfig;
    private final DaoConfig recommendFragmentDataDaoConfig;

    private final FindFragmentDataDao findFragmentDataDao;
    private final RecommendFragmentDataDao recommendFragmentDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        findFragmentDataDaoConfig = daoConfigMap.get(FindFragmentDataDao.class).clone();
        findFragmentDataDaoConfig.initIdentityScope(type);

        recommendFragmentDataDaoConfig = daoConfigMap.get(RecommendFragmentDataDao.class).clone();
        recommendFragmentDataDaoConfig.initIdentityScope(type);

        findFragmentDataDao = new FindFragmentDataDao(findFragmentDataDaoConfig, this);
        recommendFragmentDataDao = new RecommendFragmentDataDao(recommendFragmentDataDaoConfig, this);

        registerDao(FindFragmentData.class, findFragmentDataDao);
        registerDao(RecommendFragmentData.class, recommendFragmentDataDao);
    }
    
    public void clear() {
        findFragmentDataDaoConfig.getIdentityScope().clear();
        recommendFragmentDataDaoConfig.getIdentityScope().clear();
    }

    public FindFragmentDataDao getFindFragmentDataDao() {
        return findFragmentDataDao;
    }

    public RecommendFragmentDataDao getRecommendFragmentDataDao() {
        return recommendFragmentDataDao;
    }

}
