package com.my.nullpointerplayer.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FIND_FRAGMENT_DATA".
 */
public class FindFragmentData {

    private String name;
    private String response;

    public FindFragmentData() {
    }

    public FindFragmentData(String name) {
        this.name = name;
    }

    public FindFragmentData(String name, String response) {
        this.name = name;
        this.response = response;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getResponse() {
        return response;
    }

    public void setResponse(String response) {
        this.response = response;
    }

}
