package com.my.nullpointerplayer.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECOMMEND_FRAGMENT_DATA".
 */
public class RecommendFragmentData {

    private String name;
    private String response;

    public RecommendFragmentData() {
    }

    public RecommendFragmentData(String name) {
        this.name = name;
    }

    public RecommendFragmentData(String name, String response) {
        this.name = name;
        this.response = response;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getResponse() {
        return response;
    }

    public void setResponse(String response) {
        this.response = response;
    }

}
